### ISSUE TITLE
How to connect to existing window?

### ISSUE THREAD

**Issue by MTRNord** [SergeyBibikov/rust-selenium#1]
Hi I am trying to automate some of my workflow and I am starting the browser trough my window manager (basically from the console). Is there a way to hook selenium/this crate into these windows and access already open tabs trough selenium/this crate?

**Comment by SergeyBibikov** [comment]
@MTRNord Hi! Unfortunately, it is not possible due to the fact that to switch to the window you need to use a session id which is assigned by the selenium server, so you can only switch to a window created through it.

**Comment by MTRNord** [comment]
Ok thanks :)
