### ISSUE TITLE
Lack of whitespace characters

### ISSUE THREAD

**Issue by AustinHellerRepo** [SergeyBibikov/rust-selenium#3]
If we used `cargo fmt` we could format this code base such that it matches the rest of the communities' coding style. This would both make it easier for other Rust developers to contribute to the project as well as give the repository a look of professionalism.

Example:
`pub fn release_actions(&self)->Result<(),String>{`
would become
`pub fn release_actions(&self) -> Result<(), String> {`

**Comment by SergeyBibikov** [comment]
Hi! Formatted all src files :)
